.TH FOO 1
.SH NAME
foo \- an example command
.SH DESCRIPTION
.B foo
an example command.
.SH OPTIONS
.TP
.BR \-r ", " \-\-red =\fIAPPLE\fR
Option 1.
.TP
.BR \-y ", " \-\-yellow =\fIBANANA\fR
Option 2.
.TP
.BR \-r ", " \-\-bar =\fIBAR\fR
Option 3.
.TP
.BR \-b ", " \-\-bar =\fIBAR\fR
Option 4, and a quote shouldn't break this description!
.TP
.BR \--orange =\fIORANGE\fR
Option 5.
